package br.uefs.ecomp.view;

import br.uefs.ecomp.controller.Controller;
import br.uefs.ecomp.model.Noticia;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

//@author Eduardo
public class LerNoticia extends javax.swing.JDialog {
    private Controller c;
    private int idNoticia;
            
    public LerNoticia(java.awt.Frame parent, boolean modal, Controller c, int idNoticia) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/logonews.png")).getImage());
        this.c = c;
        this.idNoticia = idNoticia;
        this.exibeNoticia();
    }
    
    public LerNoticia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        setAvaliacao = new javax.swing.JButton();
        sliderAvaliacao = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        estrelaAvaliacao = new javax.swing.JLabel();
        avalia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/logonews.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("Titulo da Noticia");

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto.setLineWrap(true);
        texto.setRows(5);
        texto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(texto);

        setAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/estrela2.png"))); // NOI18N
        setAvaliacao.setText("(0)");
        setAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAvaliacaoActionPerformed(evt);
            }
        });

        sliderAvaliacao.setMaximum(5);
        sliderAvaliacao.setMinimum(1);
        sliderAvaliacao.setValue(1);
        sliderAvaliacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAvaliacaoStateChanged(evt);
            }
        });

        jLabel3.setText("Avalie a noticia:");

        estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e1.png"))); // NOI18N

        avalia.setBackground(new java.awt.Color(255, 204, 0));
        avalia.setForeground(new java.awt.Color(255, 255, 255));
        avalia.setText("Enviar");
        avalia.setEnabled(false);
        avalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(setAvaliacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sliderAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estrelaAvaliacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avalia))
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estrelaAvaliacao)
                            .addComponent(avalia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(sliderAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(setAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAvaliacaoActionPerformed
        int nota = Integer.parseInt((String) JOptionPane.showInputDialog(this, "Defina uma nota de avaliação", "Avaliação", WIDTH, new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e5.png")), null, null));
        while (nota < 0) {
            nota = Integer.parseInt((String) JOptionPane.showInputDialog(this, "Por favor, insira um valor maior que 0", "Avaliação", WIDTH, new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e5.png")), null, null));
        }
        
        int qtdNota = Integer.parseInt((String) JOptionPane.showInputDialog(this, "Defina uma quantidade de avaliações", "Avaliação", WIDTH, new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e5.png")), null, null));
        while (qtdNota < 0) {
            qtdNota = Integer.parseInt((String) JOptionPane.showInputDialog(this, "Por favor, insira um valor maior que 0", "Avaliação", WIDTH, new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e5.png")), null, null));
        }
        
        c.setAvaliacao(this.idNoticia, nota, qtdNota);
    }//GEN-LAST:event_setAvaliacaoActionPerformed

    //------------------------------------------------------------------------//
    public void exibeNoticia(){
        Noticia n = c.getNoticia(this.idNoticia);
        
        titulo.setText(n.getTitulo());
        texto.setText(n.getTexto());
        float media = (float)n.getNota()/n.getQtdNotas();
        setAvaliacao.setText(""+format(media));
    }
    
    //Formata o valor Double para 1 ou 2 casas decimais depois da virgula.
    private String format(double valor){
        DecimalFormat df = new DecimalFormat("0.#");
        String v = df.format(valor);
        return v;
    }
    //------------------------------------------------------------------------//
    private void sliderAvaliacaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAvaliacaoStateChanged
        avalia.setEnabled(true);
        
        if(sliderAvaliacao.getValue() == 1){
            estrelaAvaliacao.setText("1");
            estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e1.png")));
        }else if (sliderAvaliacao.getValue() == 2) {
            estrelaAvaliacao.setText("2");
            estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e2.png")));
        }else if(sliderAvaliacao.getValue() == 3){
            estrelaAvaliacao.setText("3");
            estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e3.png")));
        }else if(sliderAvaliacao.getValue() == 4){
            estrelaAvaliacao.setText("4");
            estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e4.png")));
        }else if(sliderAvaliacao.getValue() == 5){
            estrelaAvaliacao.setText("5");
            estrelaAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uefs/ecomp/icons/e5.png")));
        }
    }//GEN-LAST:event_sliderAvaliacaoStateChanged

    private void avaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliaActionPerformed
        int nota = sliderAvaliacao.getValue();
        c.avaliacao(nota, this.idNoticia);
        avalia.setEnabled(false);
    }//GEN-LAST:event_avaliaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LerNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LerNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LerNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LerNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LerNoticia dialog = new LerNoticia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avalia;
    private javax.swing.JLabel estrelaAvaliacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton setAvaliacao;
    private javax.swing.JSlider sliderAvaliacao;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
